#!/usr/bin/env bash
# This script will try to ping an IP address 5 times otherwise a message will appear
if [ -z "$1"]; then
echo 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}'
exit 1
fi
IP_ADDRESS = "$1"
ping -c 5 "$1"
