#!/usr/bin/env bash
# This script will assign new IP addresses to localhost and facebook.com
# This will copy all content of etc/hosts to a backup
cp /etc/hosts /etc/hosts.backup
# This will delete all content in etc/hosts
echo -n > /etc/hosts
# This will change the localhost IP address
echo "127.0.0.2 localhost" >> /etc/hosts
# This will change the facebook.com IP address
echo "8.8.8.8 facebook.com" >> /etc/hosts
